DROP DATABASE IF EXISTS task3000;
CREATE DATABASE task3000;
USE task3000;
​
​
CREATE TABLE `employee` (
id INT(30) AUTO_INCREMENT NOT NULL,
level int(30) NOT NULL ,
name VARCHAR(30) NOT NULL,
email VARCHAR(30) NOT NULL,
PRIMARY KEY (id)
);
​
​
CREATE TABLE `taskType` (
id INT(30) AUTO_INCREMENT NOT NULL,
name VARCHAR(30) NOT NULL,
PRIMARY KEY (id)
);
​
CREATE TABLE `jobs` (
id INT(30) AUTO_INCREMENT NOT NULL,
name VARCHAR(30) NOT NULL,
location VARCHAR(30) NOT NULL,
tasktype INT(30) NOT NULL,
employee_id VARCHAR(30) NOT NULL,
job_desc TEXT(125) NOT NULL,
job_status INT(1),
PRIMARY KEY (id)
